version: "3.8"

services:
    node:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:3000"
        container_name: node
        command: 
            pm2-runtime start bin/www --watch --name main
    mongo:
        image: mongo:4.4.1-bionic
        container_name: mongo
